### ISSUE TITLE
Morphological chart deeltaak

### ISSUE THREAD

**Issue by KaanKalmi** [KaanKalmi/dont-repeat-yourself-component-library#3]
Maak een morphological chart waarin je minstens acht variaties kan bedenken per component, werk daarna de componenten uit in figma.

Link + Screenshots als comment zetten

**Comment by smolgeorgie** [comment]
## Morphological chart 
![image](https://github.com/user-attachments/assets/68bd1955-1abf-45e7-9bcf-9c4c1b5b3008)
