### ISSUE TITLE
Lighthouse results

### ISSUE THREAD

**Issue by KaanKalmi** [KaanKalmi/dont-repeat-yourself-component-library#63]
Na 5 testen heb ik bij de 3de dit resultaat gekregen:

![image](https://github.com/user-attachments/assets/4c7112f0-cabc-40ea-a4bc-495ac31d730a)

> Hmmmmmm, kan ik een 100 op alles krijgen 🤔

**Comment by KaanKalmi** [comment]
> ![image](https://github.com/user-attachments/assets/01733cde-f02a-402b-aab8-db1dc8090ce2)
DESKTOP

> ![Screenshot 2024-11-25 190722](https://github.com/user-attachments/assets/75fc5782-ffe5-4f25-b06e-919a2a1553aa)
MOBILE

**Comment by KaanKalmi** [comment]
Sprint pagina :

> ![image](https://github.com/user-attachments/assets/d7432103-dd91-4438-9e95-15df23965df1)
Desktop

> ![image](https://github.com/user-attachments/assets/280516c8-12bc-4318-8c79-eb1a574f499c)
Mobiel

**Comment by KaanKalmi** [comment]
Semester pagina:

> ![image](https://github.com/user-attachments/assets/bc84132a-1b69-47e9-a00c-71b8263b0568)
Desktop

> ![image](https://github.com/user-attachments/assets/4bd878d0-0f76-4954-95e1-2895b6ff7ed2)
Mobiel

**Comment by Anna-Kyra** [comment]
Mobile:
<img width="539" alt="Scherm­afbeelding 2024-11-25 om 19 30 01" src="https://github.com/user-attachments/assets/5e3d094f-0459-4cc8-8e23-f10e28a37d33">


Desktop:
<img width="638" alt="Scherm­afbeelding 2024-11-25 om 19 26 10" src="https://github.com/user-attachments/assets/eb94f227-30a9-458b-ac64-36136dd621c9">

**Comment by KaanKalmi** [comment]
I aint even gonna lie, that's it for this sprint, lemme tend to my 🐛 now...
